spring:
  pulsar:
    client:
      service-url: ${PULSAR_URL:pulsar://10.14.0.208:6650/}
#    defaults:
#      type-mappings:
#        - message-type: com.acme.User
#          schema-info:
#            schema-type: AVRO
#        - message-type: com.acme.Address
#          schema-info:
#            schema-type: JSON

server:
  port: 8888

custom:
  pod-name: ${POD_NAME:123}